# Generated by Django 4.0 on 2021-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('range_text', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('entry_weight', models.IntegerField(default=5)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_short_entry', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('section_weight', models.IntegerField(default=5)),
                ('entries', models.ManyToManyField(blank=True, to='resume.Entry')),
            ],
        ),
    ]
